-- ==========================================
--  AssetFlow Database Schema (PostgreSQL)
-- ==========================================

-- Clean-up existing tables (if re-running script)
DROP TABLE IF EXISTS delta_logs CASCADE;
DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS item_masters CASCADE;
DROP TABLE IF EXISTS vendor_products CASCADE;
DROP TABLE IF EXISTS vendors CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS audit_items CASCADE;
DROP TABLE IF EXISTS audit_cycles CASCADE;
DROP TABLE IF EXISTS maintenance_requests CASCADE;
DROP TABLE IF EXISTS bookings CASCADE;
DROP TABLE IF EXISTS assets CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS employees CASCADE;
DROP TABLE IF EXISTS departments CASCADE;

-- ── 1. ORG SETUP & EMPLOYEES ────────────────
CREATE TABLE departments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  head TEXT,
  parent TEXT DEFAULT 'None' NOT NULL,
  status TEXT DEFAULT 'Active' CHECK (status IN ('Active', 'Inactive')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  warranty_period INT NOT NULL DEFAULT 0, -- in days
  custom_field TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE employees (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  department TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('Employee', 'Asset Manager', 'Department Head', 'Admin')),
  status TEXT DEFAULT 'Active' CHECK (status IN ('Active', 'Inactive')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── 2. ASSETS & RESERVATIONS ────────────────
CREATE TABLE assets (
  tag TEXT PRIMARY KEY, -- e.g., 'AF-0114'
  name TEXT NOT NULL,
  category TEXT NOT NULL REFERENCES categories(name) ON UPDATE CASCADE,
  serial TEXT UNIQUE NOT NULL,
  cost NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
  condition TEXT NOT NULL CHECK (condition IN ('New', 'Good', 'Fair', 'Damaged', 'Missing')),
  status TEXT NOT NULL CHECK (status IN ('Available', 'Allocated', 'Reserved', 'Under Maintenance', 'Lost', 'Retired', 'Disposed')),
  location TEXT NOT NULL,
  holder TEXT DEFAULT 'None' NOT NULL, -- name of employee or 'Shared' or 'None'
  shared BOOLEAN DEFAULT FALSE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resource TEXT NOT NULL, -- references asset name or tag
  user_name TEXT NOT NULL, -- references employee name
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  booking_date DATE NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('Upcoming', 'Ongoing', 'Completed', 'Cancelled')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── 3. MAINTENANCE & COMPLIANCE AUDITS ──────
CREATE TABLE maintenance_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  asset_tag TEXT REFERENCES assets(tag) ON DELETE CASCADE NOT NULL,
  description TEXT NOT NULL,
  priority TEXT NOT NULL CHECK (priority IN ('Low', 'Medium', 'High')),
  status TEXT NOT NULL CHECK (status IN ('Pending', 'Approved', 'Technician Assigned', 'In Progress', 'Resolved')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE audit_cycles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scope TEXT NOT NULL,
  auditor TEXT NOT NULL,
  date_range TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('Active', 'Closed')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE audit_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  audit_cycle_id BIGINT REFERENCES audit_cycles(id) ON DELETE CASCADE NOT NULL,
  asset_tag TEXT REFERENCES assets(tag) ON DELETE CASCADE NOT NULL,
  audited_status TEXT NOT NULL CHECK (audited_status IN ('Unchecked', 'Verified', 'Missing', 'Damaged')),
  UNIQUE(audit_cycle_id, asset_tag)
);

-- ── 4. PROCUREMENT HUB (ITEM MASTER & POs) ──
CREATE TABLE products (
  id TEXT PRIMARY KEY, -- e.g., 'P001'
  name TEXT NOT NULL,
  category TEXT NOT NULL CHECK (category IN ('Raw Material', 'Semi-Finished Material', 'Finished Material')),
  description TEXT,
  sku TEXT UNIQUE NOT NULL,
  unit_of_measure TEXT NOT NULL
);

CREATE TABLE vendors (
  id TEXT PRIMARY KEY, -- e.g., 'V001'
  name TEXT NOT NULL,
  shop_name TEXT NOT NULL,
  location TEXT NOT NULL,
  contact_email TEXT NOT NULL,
  contact_phone TEXT NOT NULL
);

CREATE TABLE vendor_products (
  vendor_id TEXT REFERENCES vendors(id) ON DELETE CASCADE,
  product_id TEXT REFERENCES products(id) ON DELETE CASCADE,
  price NUMERIC(10, 2) NOT NULL,
  in_stock BOOLEAN NOT NULL DEFAULT TRUE,
  min_order_qty INT NOT NULL DEFAULT 1,
  PRIMARY KEY (vendor_id, product_id)
);

CREATE TABLE item_masters (
  id TEXT PRIMARY KEY, -- e.g., 'IM001'
  name TEXT NOT NULL,
  sku TEXT NOT NULL REFERENCES products(sku) ON UPDATE CASCADE,
  material_category TEXT NOT NULL CHECK (material_category IN ('Raw Material', 'Semi-Finished Material', 'Finished Material')),
  quantity INT NOT NULL DEFAULT 0,
  rate NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
  material_location TEXT NOT NULL,
  company_name TEXT NOT NULL,
  description TEXT
);

CREATE TABLE orders (
  id TEXT PRIMARY KEY, -- e.g., 'ORD001'
  order_number TEXT UNIQUE NOT NULL,
  date DATE NOT NULL,
  customer TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('Draft', 'Confirmed', 'In Progress', 'Completed', 'Cancelled')),
  notes TEXT
);

CREATE TABLE order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id TEXT REFERENCES orders(id) ON DELETE CASCADE,
  product_id TEXT REFERENCES products(id),
  product_name TEXT NOT NULL,
  quantity INT NOT NULL,
  unit_price NUMERIC(10, 2) NOT NULL,
  vendor_id TEXT REFERENCES vendors(id),
  vendor_name TEXT NOT NULL,
  material_category TEXT NOT NULL
);

-- ── 5. NOTIFICATIONS & COMPLIANCE LOGS ──────
CREATE TABLE notifications (
  id TEXT PRIMARY KEY, -- e.g., 'N001'
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('alert', 'info', 'success', 'warning')),
  is_read BOOLEAN DEFAULT FALSE NOT NULL,
  target_user_id TEXT NOT NULL, -- 'all' or user email
  created_at TIMESTAMPTZ DEFAULT NOW(),
  link TEXT
);

CREATE TABLE delta_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  timestamp TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  actor TEXT NOT NULL,
  action TEXT NOT NULL,
  asset_tag TEXT,
  detail TEXT NOT NULL
);
