import pg from 'pg';
import dotenv from 'dotenv';
import fs from 'fs';
import path from 'path';

dotenv.config();

const { Pool } = pg;
const connectionString = process.env.DATABASE_URL;

const realPool = new Pool({
  connectionString,
  ssl: connectionString?.includes('supabase.co') || connectionString?.includes('supabase.com')
    ? { rejectUnauthorized: false }
    : false
});

export let useSQLite = false;
let sqliteDb: any = null;

// Mock Pool for SQLite compatibility
export const pool: any = {
  on: () => {},
  connect: async () => {
    if (useSQLite) {
      return {
        query: (text: string, params?: any[]) => query(text, params),
        release: () => {}
      };
    } else {
      return realPool.connect();
    }
  },
  end: async () => {
    if (!useSQLite) {
      await realPool.end();
    }
  }
};

// Check database connection and set up fallback
const initDB = async () => {
  try {
    // Attempt connection to PG
    const client = await realPool.connect();
    client.release();
    console.log('⚡ Connected to PostgreSQL Database successfully.');
  } catch (err) {
    console.warn('⚠️ Warning: Failed to connect to PostgreSQL database. Switching to local SQLite fallback...');
    useSQLite = true;
    
    try {
      // Bypassing TS compiler checks for node:sqlite by using eval dynamic import
      const sqliteModule = await eval("import('node:sqlite')") as any;
      const DatabaseSync = sqliteModule.DatabaseSync;
      
      // Resolve path to database file in backend root (using __dirname since output is CJS)
      const dbPath = path.resolve(__dirname, '../../assetflow.db');
      console.log(`📂 Initializing SQLite database at: ${dbPath}`);
      sqliteDb = new DatabaseSync(dbPath);
      
      // Check if schema needs creation
      const tableCheck = sqliteDb.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='employees'").all();
      if (tableCheck.length === 0) {
        console.log('⚙️ No existing tables found. Creating SQLite schema and seeding data...');
        await setupSqliteSchema();
      } else {
        console.log('⚡ Local SQLite database is ready.');
      }
    } catch (sqliteErr) {
      console.error('❌ Critical: Failed to load built-in node:sqlite module:', sqliteErr);
    }
  }
};

// Programmatic schema setup and translation for SQLite
const setupSqliteSchema = async () => {
  try {
    const schemaPath = path.resolve(__dirname, '../../schema.sql');
    if (!fs.existsSync(schemaPath)) {
      console.error(`❌ Schema file not found at: ${schemaPath}`);
      return;
    }
    
    const schemaText = fs.readFileSync(schemaPath, 'utf8');
    
    // Translate schema from PG syntax to SQLite syntax
    const sqliteQueries = schemaText
      .replace(/DROP TABLE IF EXISTS (\w+) CASCADE/gi, 'DROP TABLE IF EXISTS $1')
      .replace(/BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY/gi, 'INTEGER PRIMARY KEY AUTOINCREMENT')
      .replace(/BIGINT REFERENCES/gi, 'INTEGER REFERENCES')
      .replace(/BIGINT/gi, 'INTEGER')
      .replace(/TIMESTAMPTZ/gi, 'TEXT')
      .replace(/NUMERIC\(\d+,\s*\d+\)/gi, 'REAL')
      .replace(/NUMERIC/gi, 'REAL')
      .replace(/ON UPDATE CASCADE/gi, '')
      .replace(/DEFAULT NOW\(\)/gi, "DEFAULT (datetime('now'))");
      
    // Execute DDL statements (SQLite allows multiple queries via exec)
    sqliteDb.exec(sqliteQueries);
    console.log('✅ SQLite Schema created successfully.');
    
    // Run seeding
    await seedSqlite();
  } catch (error) {
    console.error('❌ Failed to construct SQLite schema:', error);
  }
};

// Seed SQLite with mock users
const seedSqlite = async () => {
  try {
    console.log('🌱 Seeding local SQLite database...');
    const bcrypt = require('bcryptjs');
    const salt = await bcrypt.genSalt(10);
    const passHash = await bcrypt.hash('admin123', salt);
    
    // Insert seeded departments, categories, and Admin Employee
    sqliteDb.exec(`
      INSERT INTO departments (name, head, parent, status) VALUES
      ('Engineering', 'Marcus Brody', 'None', 'Active'),
      ('Design', 'Raj Patel', 'Engineering', 'Active'),
      ('Operations', 'Alex Mercer', 'None', 'Active'),
      ('Audit & Compliance', 'Sarah Jenkins', 'Operations', 'Active');
      
      INSERT INTO categories (name, warranty_period, custom_field) VALUES
      ('Electronics', 365, 'CPU / RAM specs'),
      ('Furniture', 1095, 'Material type'),
      ('Vehicles', 730, 'License Plate'),
      ('Office Spaces', 0, 'Capacity');
    `);
    
    // Insert default users dynamically hashed
    const stmt = sqliteDb.prepare(`
      INSERT INTO employees (name, email, password_hash, department, role, status)
      VALUES 
      ('Rishikesh Singh', 'admin@assetflow.com', ?, 'Operations', 'Admin', 'Active'),
      ('Sarah Jenkins', 'manager@assetflow.com', ?, 'Operations', 'Asset Manager', 'Active'),
      ('Raj Patel', 'head@assetflow.com', ?, 'Engineering', 'Department Head', 'Active'),
      ('Priya Sharma', 'employee@assetflow.com', ?, 'Engineering', 'Employee', 'Active')
    `);
    stmt.run(passHash, passHash, passHash, passHash);

    // Seed core assets
    sqliteDb.exec(`
      INSERT INTO assets (tag, name, category, serial, cost, condition, status, location, holder, shared) VALUES
      ('AF-0114', 'MacBook Pro M3', 'Electronics', 'S/N 83B4F83', 2500.00, 'New', 'Allocated', 'HQ - Floor 3', 'Priya Sharma', 0),
      ('AF-0341', 'Dell XPS 15', 'Electronics', 'S/N 29A4D19', 1800.00, 'Good', 'Available', 'HQ - Floor 2', 'None', 0),
      ('AF-0883', 'Herman Miller Aeron', 'Furniture', 'S/N 12B8C73', 1200.00, 'Good', 'Available', 'HQ - Room A1', 'None', 0),
      ('AF-1002', 'Conference Room B2', 'Office Spaces', 'LOC-B2', 0.00, 'New', 'Available', 'HQ - Floor 1', 'Shared', 1),
      ('AF-0220', 'Tesla Model 3', 'Vehicles', 'PLATE-AURA', 42000.00, 'Good', 'Available', 'Garage A', 'Shared', 1);
      
      INSERT INTO bookings (resource, user_name, start_time, end_time, booking_date, status) VALUES
      ('Conference Room B2', 'Raj Patel', '09:00:00', '10:00:00', '2026-07-12', 'Ongoing');
      
      INSERT INTO maintenance_requests (asset_tag, description, priority, status) VALUES
      ('AF-0341', 'Keyboard double space defect', 'Medium', 'Pending');
      
      INSERT INTO audit_cycles (scope, auditor, date_range, status) VALUES
      ('Engineering Department', 'Sarah Jenkins', '2026-07-10 - 2026-07-15', 'Active');
      
      INSERT INTO audit_items (audit_cycle_id, asset_tag, audited_status) VALUES
      (1, 'AF-0114', 'Unchecked'),
      (1, 'AF-0341', 'Unchecked'),
      (1, 'AF-0883', 'Unchecked');
    `);

    // Seed products
    sqliteDb.exec(`
      INSERT INTO products (id, name, category, description, sku, unit_of_measure) VALUES
      ('P001', 'Steel Rod 12mm', 'Raw Material', 'High tensile steel rod', 'SR-12MM-001', 'kg'),
      ('P002', 'Copper Wire 2.5mm', 'Raw Material', 'Electrical grade copper wire', 'CW-25MM-002', 'meter'),
      ('P003', 'Industrial Bearing 6205', 'Semi-Finished Material', 'Deep groove ball bearing', 'IB-6205-003', 'unit'),
      ('P004', 'Motor Drive PCB', 'Semi-Finished Material', 'Partially assembled motor PCB', 'PCB-MD-004', 'unit'),
      ('P005', 'Hydraulic Pump Assembly', 'Finished Material', 'Complete hydraulic pump', 'HPA-V2-005', 'unit'),
      ('P006', 'Stainless Sheet 2mm', 'Raw Material', '304 grade stainless steel sheet', 'SS-2MM-006', 'sqft'),
      ('P007', 'Pneumatic Cylinder 50mm', 'Finished Material', 'Ready-to-install pneumatic cylinder', 'PC-50MM-007', 'unit'),
      ('P008', 'Gear Assembly Kit', 'Semi-Finished Material', 'Partially machined gear set', 'GAK-V1-008', 'set'),
      ('P009', 'Aluminium Ingot 99%', 'Raw Material', 'Primary aluminium ingot', 'AI-99P-009', 'kg'),
      ('P010', 'Electric Motor 2HP', 'Finished Material', 'Single phase induction motor', 'EM-2HP-010', 'unit'),
      ('P011', 'PVC Granules', 'Raw Material', 'Virgin grade PVC resin granules', 'PVC-GR-011', 'kg'),
      ('P012', 'Control Panel Box', 'Finished Material', 'IP65 rated control panel enclosure', 'CPB-IP65-012', 'unit');
      
      INSERT INTO vendors (id, name, shop_name, location, contact_email, contact_phone) VALUES
      ('V001', 'Ravi Steels Pvt Ltd', 'Ravi Metal Works', 'MIDC Phase II, Pune - 411019', 'ravi@ravisteels.com', '+91-9876541001'),
      ('V002', 'Arjun Electricals', 'AE Electrical Supplies', 'Industrial Area, Nashik - 422001', 'supply@arjunelec.in', '+91-9876541002'),
      ('V003', 'Precision Bearings Co.', 'PBC Warehouse', 'Bhosari MIDC, Pune - 411026', 'orders@pbc.co.in', '+91-9876541003'),
      ('V004', 'Suresh Hydraulics', 'SH Fluid Power', 'Chakan Industrial Zone, Pune - 410501', 'sales@sureshhydraulics.com', '+91-9876541004'),
      ('V005', 'Polymer Solutions Ltd', 'PSL Depot', 'Talegaon MIDC, Pune - 412106', 'polymer@psl.in', '+91-9876541005'),
      ('V006', 'MegaMetal Traders', 'MegaMetal Yard', 'Hadapsar, Pune - 411028', 'trade@megametal.in', '+91-9876541006');
      
      INSERT INTO vendor_products (vendor_id, product_id, price, in_stock, min_order_qty) VALUES
      ('V001', 'P001', 82.50, 1, 100),
      ('V001', 'P006', 145.00, 1, 50),
      ('V001', 'P009', 210.00, 0, 200),
      ('V002', 'P002', 58.00, 1, 500),
      ('V002', 'P004', 1250.00, 1, 10),
      ('V002', 'P010', 4800.00, 1, 1),
      ('V003', 'P003', 320.00, 1, 20),
      ('V003', 'P008', 2100.00, 1, 5),
      ('V004', 'P005', 18500.00, 1, 1),
      ('V004', 'P007', 3200.00, 1, 2),
      ('V005', 'P011', 95.00, 1, 500),
      ('V005', 'P012', 6800.00, 0, 1),
      ('V006', 'P001', 79.00, 1, 200),
      ('V006', 'P006', 138.00, 1, 100),
      ('V006', 'P009', 205.00, 1, 500);

      INSERT INTO item_masters (id, name, sku, material_category, quantity, rate, material_location, company_name, description) VALUES
      ('IM001', 'Steel Rod 12mm', 'SR-12MM-001', 'Raw Material', 500, 80.00, 'Warehouse A - Rack 3', 'In-House Production', 'Primary raw material for fabrication'),
      ('IM002', 'Motor Drive PCB', 'PCB-MD-004', 'Semi-Finished Material', 25, 1200.00, 'Assembly Bay - Zone 2', 'Arjun Electricals', 'Requires final component soldering in-house'),
      ('IM003', 'Hydraulic Pump Assembly', 'HPA-V2-005', 'Finished Material', 8, 18000.00, 'Store Room B - Shelf 1', 'Suresh Hydraulics', 'Fully vendor-manufactured, ready for dispatch'),
      ('IM004', 'Copper Wire 2.5mm', 'CW-25MM-002', 'Raw Material', 2000, 56.00, 'Warehouse A - Rack 7', 'In-House Drawn', 'Electrical wiring raw stock'),
      ('IM005', 'Gear Assembly Kit', 'GAK-V1-008', 'Semi-Finished Material', 15, 2000.00, 'Assembly Bay - Zone 4', 'Precision Bearings Co.', 'Requires final balancing and heat treatment in-house');
      
      INSERT INTO orders (id, order_number, date, customer, status, notes) VALUES
      ('ORD001', 'PO-2026-001', '2026-07-10', 'ABC Manufacturing Ltd', 'Confirmed', 'Urgent delivery required'),
      ('ORD002', 'PO-2026-002', '2026-07-08', 'XYZ Engineering Works', 'Confirmed', ''),
      ('ORD003', 'PO-2026-003', '2026-07-05', 'Delta Auto Parts', 'Completed', 'Monthly standing order');

      INSERT INTO order_items (order_id, product_id, product_name, quantity, unit_price, vendor_id, vendor_name, material_category) VALUES
      ('ORD001', 'P001', 'Steel Rod 12mm', 500, 82.50, 'V001', 'Ravi Steels Pvt Ltd', 'Raw Material'),
      ('ORD001', 'P003', 'Industrial Bearing 6205', 50, 320.00, 'V003', 'Precision Bearings Co.', 'Semi-Finished Material'),
      ('ORD002', 'P005', 'Hydraulic Pump Assembly', 3, 18500.00, 'V004', 'Suresh Hydraulics', 'Finished Material'),
      ('ORD003', 'P002', 'Copper Wire 2.5mm', 1000, 58.00, 'V002', 'Arjun Electricals', 'Raw Material'),
      ('ORD003', 'P010', 'Electric Motor 2HP', 5, 4800.00, 'V002', 'Arjun Electricals', 'Finished Material');
      
      INSERT INTO notifications (id, title, message, type, is_read, target_user_id, created_at, link) VALUES
      ('N001', '⚠ Low Stock Alert', 'Steel Rod 12mm (SR-12MM-001) has only 500 units — below threshold of 1,000 for Raw Materials.', 'alert', 0, 'all', datetime('now', '-2 hours'), 'itemmaster'),
      ('N002', '✅ Order Placed', 'Order PO-2026-001 for ABC Manufacturing Ltd confirmed. Total: ₹57,250.', 'success', 0, 'all', datetime('now', '-5 hours'), 'orders'),
      ('N003', '📄 BOM Generated', 'Bill of Materials auto-generated for PO-2026-001 with 2 line items totalling ₹57,250.', 'info', 1, 'all', datetime('now', '-5 hours'), 'orders'),
      ('N004', '⚠ Low Stock Alert', 'Gear Assembly Kit (GAK-V1-008) has only 15 units — below threshold of 20 for Semi-Finished Materials.', 'alert', 0, 'all', datetime('now', '-24 hours'), 'itemmaster'),
      ('N005', '✅ Order Placed', 'Order PO-2026-002 for XYZ Engineering Works confirmed. Total: ₹55,500.', 'success', 1, 'all', datetime('now', '-30 hours'), 'orders'),
      ('N006', '⚠ Low Stock Alert', 'Hydraulic Pump Assembly (HPA-V2-005) has only 8 units — below threshold of 10 for Finished Materials.', 'alert', 0, 'all', datetime('now', '-48 hours'), 'itemmaster');
      
      INSERT INTO delta_logs (timestamp, actor, action, detail) VALUES
      (datetime('now', '-10 hours'), 'System Seed Engine', 'INITIALIZE_DB', 'Pre-populated core assets, employee directory, and departments.'),
      (datetime('now', '-9 hours'), 'Marcus Brody (Admin)', 'ROLE_ELEVATION', 'Priya Sharma promoted to Asset Manager permissions.');
    `);
    
    console.log('🎉 SQLite Database seeded successfully.');
  } catch (error) {
    console.error('❌ Failed to seed SQLite database:', error);
  }
};

// Unified Query Handler with PostgreSQL/SQLite routing and translations
export const query = async (text: string, params: any[] = []) => {
  const start = Date.now();
  try {
    if (useSQLite) {
      // Translate numbered bind variables ($1, $2) to positional bindings (?)
      const sqliteSql = text
        .replace(/\$\d+/g, '?')
        .replace(/NOW\(\)/gi, "datetime('now')"); // translate NOW() to SQLite datetime('now')
      
      // Determine if statement returns rows
      const isQueryReturningRows = sqliteSql.toLowerCase().includes('select') || sqliteSql.toLowerCase().includes('returning');
      
      const stmt = sqliteDb.prepare(sqliteSql);
      
      // Map booleans to SQLite integers (1/0)
      const mappedParams = params.map(p => typeof p === 'boolean' ? (p ? 1 : 0) : p);
      
      if (isQueryReturningRows) {
        const rows = stmt.all(...mappedParams) as any[];
        
        // SQLite converts boolean columns to numbers. Map back to true/false for frontend fields
        const mappedRows = rows.map(row => {
          const newRow = { ...row };
          if ('shared' in newRow) {
            newRow.shared = !!newRow.shared;
          }
          if ('isRead' in newRow) {
            newRow.isRead = !!newRow.isRead;
          }
          if ('is_read' in newRow) {
            newRow.is_read = !!newRow.is_read;
          }
          return newRow;
        });
        
        return { rows: mappedRows, rowCount: mappedRows.length };
      } else {
        const res = stmt.run(...mappedParams) as any;
        return { rows: [], rowCount: res.changes };
      }
    } else {
      const res = await realPool.query(text, params);
      const duration = Date.now() - start;
      console.log(`🔍 PG Executed query [${duration}ms]:`, { text: text.trim().substring(0, 80) + '...', rowsCount: res.rowCount });
      return res;
    }
  } catch (error) {
    console.error('❌ Query execution failed:', { text, error });
    throw error;
  }
};

// Run initialization
initDB();
